### ISSUE TITLE
Add Product#constructCalendar that builds first set of timeSlots given monthlyTimeSlotDaysBatchSize

### ISSUE THREAD

**Issue by nicklandgrebe** [GetOccasion/occasion-sdk-js#17]
## Stories

* As a developer, I want to be able to easily display a calendar of time slots for given product for any given month to my customers

## TODOs

- [x] Write specs
- [x] Wrap `product.firstTimeSlotStartsAt` in moment object
- [x] Wrap `timeSlot.startsAt` in moment object
- [x] Wrap `timeSlot.duration` in moment.duration object
- [x] Interpret `monthlyTimeSlotDaysBatchSize` to request month of timeSlots
- [x] Return Collection of formatted moment durations + timeSlots by day
- [x] Preload `monthlyTimeSlotPreloadSize` months so `calendar.nextPage()` easily loads the next month of time Slots
