### ISSUE TITLE
Increase or decrease order.attendees size according to updates to quantity using `afterRequest` callback

### ISSUE THREAD

**Issue by nicklandgrebe** [GetOccasion/occasion-sdk-js#18]
## Stories

* As a developer, when the quantity of my order changes, I want to have attendees built onto or popped off the order so that attendees size always matches quantity

## Implementation Plan

* Add `afterRequest` callback to order that:
  - Iteratively calls `attendees().build` if order.quantity has increased above `attendees.size()`
  - Iteratively calls `attendees().pop` if order.quantity has decreased below `attendees.size()`

## TODOs

- [x] Add `afterRequest` logic
- [x] Add `build` logic
- [x] Add `pop` logic
