### ISSUE TITLE
Auto-select timeSlots in Order#construct when product does not require timeSlot selection

### ISSUE THREAD

**Issue by nicklandgrebe** [GetOccasion/occasion-sdk-js#25]
### Stories

* As an SDK developer, I want the SDK to automatically select timeSlots for products that are sessions or only have one timeSlots

### Implementation Plan

When `product.requiresTimeSlotsSelection` is false, determine if product `sellsSessions`, and if so, load/select all timeSlots for session, otherwise load the 1 timeSlot for the product and select it

### TODO

- [x] Add check for `product.requiresTimeSlotsSelection` in `Order#construct`
- [x] If flag present, load product timeSlots
- [x] After loading timeSlots, assign them to order
